#ifndef DISCOGSINFORMATIONDETECTORPLUGIN_GLOBAL_H
#define DISCOGSINFORMATIONDETECTORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISCOGSINFORMATIONDETECTORPLUGIN_LIBRARY)
#  define DISCOGSINFORMATIONDETECTORPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISCOGSINFORMATIONDETECTORPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DISCOGSINFORMATIONDETECTORPLUGIN_GLOBAL_H
